pay/urls.py
from django.conf.urls import patterns, url
from pay.views import PaymentWizard, FORMS

payment_wizard = PaymentWizard.as_view(FORMS, url_name='pay_step', done_step_name='finished')





urlpatterns = patterns('',
    url(r'^$', payment_wizard, name='pay'),
    url(r'^(?P<step>.+)/$', payment_wizard, name='pay_step'),
)

roja/urls.py
from django.conf.urls import patterns, include, url
from pay import views
from django.contrib import admin
from django.conf.urls import patterns, url
from pay.views import PaymentWizard, FORMS
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required


payment_wizard = PaymentWizard.as_view(FORMS, url_name='pay_step', done_step_name='finished')

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rojame.views.home', name='home'),
    url(r'^$', views.HomePageView.as_view(), name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^pay/', include('pay.urls', namespace="pay")),
    url(r'^accounts/', include('allauth.urls')),
    #url(r'^accounts/', include('customer.urls')),
    
    url(r'^pay/(?P<step>.+)/$', payment_wizard, name='pay_step'),
    url(r'^pay/$', payment_wizard, name='pay'), 
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mypage/$', views.TableView.as_view(template_name='pay/table-datatable.html'), name='mypage'),
    url(r'^mypage/js/data/', login_required(views.JsonList.as_view()), name='json_list')
)

"""
urlpatterns = patterns('',
    url(r'^$', views.pay, name='pay'),
)
"""

pay/models.py
"""
Contains regualar database elements as per Django,
but also business logic and also the two constants:
BASIC_CHARGE and STRIPE_COST. STRIPE_COST is so labeled
because this is the official stripe charge for their
services. These are considered for inclusion in the
settings. If this is the case the importation should minimize
code refactoring
"""

from django.db import models
from django.contrib.auth.models import User
from random import randrange
from roja import settings


BASIC_CHARGE = settings.BASIC_CHARGE
STRIPE_COST = settings.STRIPE_COST

class ExchangeRate(models.Model):
    "Exchange rate takes value and automatically has a time-stamp"

    value = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateTimeField(auto_now=True)
   
    def __unicode__(self):
        return str(self.value)


def latest_rate():
    """
    Creates the initial rate in the database, if it does not exist.
    """
    rate = ExchangeRate.objects.latest('date')
    return rate

def random_id():
    "Generates id for use as reference in bank payments."

    charge_letters = ''
    charge_numbers = ''
    for i in range(3):
        charge_letters += (str(chr(randrange(65,90))))
    for j in range(5):
        charge_numbers += (str(randrange(10)))
    return '%s%s' %(charge_letters, charge_numbers)
    
def charge_logic(amount):
    """
    Generates the basic charge for any transaction.
    The charge is increased by one unit of the constant
    BASIC_CHARGE for every 100 pounds
    """

    if amount <= 100:
        return BASIC_CHARGE * 1
    else:
        if amount%100 == 0:
            return BASIC_CHARGE * (amount/100)
        else:
            return (BASIC_CHARGE * (amount/100)) + BASIC_CHARGE


class IntegerRangeField(models.IntegerField):
    """
    A custom field that subclasses the IntegerField and adds
    min and max values
    """

    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value':self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)

#The following allows south to introspect the above custom field
from south.modelsinspector import add_introspection_rules

add_introspection_rules([
    (
        [IntegerRangeField],
        [],
        {
            'min_value': ['min_value', {'min_value': None}],
            'max_value': ['max_value', {'max_value': None}],
        },
    ),
], ['^pay\.models\.IntegerRangeField'])

    
class Sender(models.Model):
    user = models.OneToOneField(User)
    phone = phone = models.CharField(max_length=15)
    house_no = models.CharField(max_length=10, blank=True)
    street_no = models.CharField(max_length=30, blank=True)
    city_town = models.CharField(max_length=30, blank=True)
    postcode = models.CharField(max_length=8, blank=True)
    stripe_id = models.CharField(max_length=100, blank=True)

    def _get_full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.user.first_name, self.user.last_name)
    full_name = property(_get_full_name)

    def __unicode__(self):
        return str(self.full_name)

class Receiver(models.Model):
    sender = models.ForeignKey(Sender, null=True, blank=True)

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    bank_name = models.CharField(max_length=30)
    bank_account = models.CharField(max_length=15)
    bank_location = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=254, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)

    def _get_full_name(self):
        "Returns the person's full name."
        return '%s %s' % (self.first_name, self.last_name)
    full_name = property(_get_full_name)

    def __unicode__(self):
        return str(self.full_name)

class AmountToSend(models.Model):
    sender = models.ForeignKey(Sender, null=True, blank=True)
    rate = models.ForeignKey(ExchangeRate, null=True, blank=True)
    receiver = models.ForeignKey(Receiver, null=True, blank=True)

    amount = IntegerRangeField(min_value=0, max_value=1000)

    payment_complete = models.BooleanField(default=False)
    transfer_complete = models.BooleanField(default=False)
    BANK = 'bank'
    CARD = 'card'
    PAYMENT_CHOICES = (
        ('bank', 'Pay by Bank Transfer'),
        ('card', 'Pay by Card'),
        )
    payment_choice = models.CharField(max_length=4, choices=PAYMENT_CHOICES)

    stripe_charge_id = models.CharField(max_length=250, blank=True)
    native_charge_id = models.CharField(max_length=8, blank=True)
    date_sent = models.DateTimeField(auto_now_add=True, editable=False)

    def charge(self):
        if self.payment_choice == 'bank':
            return charge_logic(self.amount)
        if self.payment_choice == 'card':
            return int(charge_logic(self.amount) + (self.amount * STRIPE_COST))

    def gbp_total(self):
        charge_calc = self.charge()
        return self.amount + charge_calc

    def ngn_total(self):
        return int(self.rate.value * self.amount)

    def __unicode__(self):
        return str(self.amount)

pay/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""

"""

from django.http import HttpResponseRedirect, HttpResponse
import stripe
from django.shortcuts import render, render_to_response
import roja.settings as settings
from django.contrib.formtools.wizard.views import NamedUrlSessionWizardView
from pay import forms, models
from pay.models import random_id, ExchangeRate
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login, logout
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.contrib.auth.views import login
from django.template.context import RequestContext
from django.views.generic.list import ListView
import json

from django.db.models.signals import post_save
from django.dispatch import receiver

from django_datatables_view.base_datatable_view import BaseDatatableView

RATE = models.latest_rate()

FORMS = [
    ("amount", forms.AmountToSendForm),
    ("confirm_amount", forms.ConfirmAmountForm),
    ("receiver", forms.ReceiverForm),
    ("card", forms.CardPaymentForm),
    ("bank", forms.BankPaymentForm),
]

TEMPLATES = {
    "amount": "pay/amount.html",
    "confirm_amount": "pay/amount_calculated.html",
    "receiver": "pay/receiver.html",
    "card": "pay/card_form.html",
    "bank": "pay/bank_success.html",
}

class TableView(ListView):
    """
    This view populates the sender's home page with
    his/her transactions and their promotional status
    """

    model = models.AmountToSend

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        """
        Used to force login for this view
        """
        return super(TableView, self).dispatch(*args, **kwargs)
    

class JsonList(TemplateView):

    model = models.AmountToSend

    def get_initial_queryset(self):
        user = self.request.user
        return self.model.objects.filter(sender=user.sender)

    def prepare_results(self):
        json_data = []
        qs = self.get_initial_queryset()
        for item in qs:
            charge_id = bool(item.native_charge_id) # Just to be neat
            json_data.append({
                'amount': "%s %s%s" % (u"£", item.amount, '.00'),
                'receiver': item.receiver.__unicode__(),
                'date': item.date_sent.strftime("%m/%d/%Y -  %H:%M"),
                'charge_id': item.native_charge_id if bool(charge_id) else "Paid by Card",
                'payment': "Processed" if item.payment_complete else "Unprocessed",
                'transfer_complete': "Done." if bool(item.transfer_complete) else "Not Yet.",
                'charge': "%s %s%s" % (u'£', item.charge(), '.00')
            })
        ready_json = {"data": json_data}
        return ready_json         
     
    def get(self, request, *args, **kwargs):
        data = self.prepare_results()
        return HttpResponse(
            json.dumps(data),
            content_type="application/json"
        )

class HomePageView(TemplateView):
    template_name = "pay/index.html"


def pay_by_card(wizard):
    """Return true if user opts to pay by credit card"""
    # Get cleaned data from payment step
    cleaned_data = wizard.get_cleaned_data_for_step('amount') or {'method': 'none'}
    # Return the value of payment_choice
    return cleaned_data.get('payment_choice') == 'card'

def pay_by_bank_transfer(wizard):
    """Return true if user opts to pay by bank transfer"""
    # Get cleaned data from payment step
    cleaned_data = wizard.get_cleaned_data_for_step('amount') or {'method': 'none'}
    # Return the value of payment_choice
    return cleaned_data.get('payment_choice') == 'bank'

def login_user(request):
    "Return Django default login"
    return login(
        request, template_name='pay/login.html',
        authentication_form=forms.LoginForm
    )

def logout_view(request):
    logout(request)
    return render(request, 'pay/logged_out.html')

def register(request):
    """
    Register new user. Uses two forms
    """
    context = RequestContext(request)
    registered = False
    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        sender_form = forms.SenderForm(data=request.POST)
        if user_form.is_valid() and sender_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            sender = sender_form.save(commit=False)
            sender.user = user
            sender.save()
            #required for the next line to work or will get error
            # "'User' object has no attribute 'backend'
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            auth_login(request, user)
            registered = True
    else:
        user_form = forms.UserForm()
        sender_form = forms.SenderForm()
    return render_to_response(
        'pay/register.html', {
            'user_form': user_form,
            'sender_form': sender_form,
            'registered': registered
        },
        context
    )
    
class PaymentWizard(NamedUrlSessionWizardView):
    
    condition_dict = {'card': pay_by_card, 'bank': pay_by_bank_transfer}
    
    def get_form_initial(self,step):
        unbound_sender = models.Sender()
        unbound_receiver = models.Receiver()
        if step == 'amount':
            self.initial_dict['amount'] = {
                'sender' : unbound_sender,
                'rate' : RATE,
                'receiver' : unbound_receiver,
            }
        if step == 'receiver':
            try:
                user = self.request.user #user signed in at this time
                sender = user.sender #using the one-to-one relationship
                self.initial_dict['receiver'] = {'sender' : sender}
            except AttributeError:
                pass
        return self.initial_dict.get(step, {})
    
    
    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def get_context_data(self, form, **kwargs):
        """
        This modification allows required data to be updated for the 
        steps confirm_amount, bank and card.
        """
        context = super(PaymentWizard, self).get_context_data(form=form, **kwargs)
        cleaned_data = super(PaymentWizard, self).get_cleaned_data_for_step('amount') or {'method': 'none'}
        
        payment_choice = cleaned_data.get('payment_choice')
        
        if cleaned_data.get('amount'):
            amount_to_send = forms.AmountToSendForm(cleaned_data)
            amount_sent = amount_to_send.save(commit=False)
            amount_sent.rate = RATE
            amount = amount_sent.amount
            if self.steps.current == 'confirm_amount' or 'bank' or 'card' and not None:
                updates = ({'input_amount': amount},
                {'payment_choice': payment_choice},           
                {'charge': amount_sent.charge},
                {'GBP_total': amount_sent.gbp_total},
                {'NGN_total': amount_sent.ngn_total},
                {'payment_id' : random_id()},
                )
                for update in updates:
                    context.update(update)
        return context
    
    def dispatch(self, *args, **kwargs):
        """
        Modify the dispatch method so that the login_required decorator can fire
        """
        url = self.request.path_info
    
        if url == u'/pay/%s/' %('receiver' or 'card' or 'bank'):
            @method_decorator(login_required)
            def inner_dispatch(self, *args, **kwargs):
                return super(PaymentWizard, self).dispatch(*args, **kwargs)
            return inner_dispatch(self, *args, **kwargs)               
        response = super(PaymentWizard, self).dispatch(*args, **kwargs) 
        return response

    def done(self, form_list, **kwargs):
        """
        Mostly save everything collected by wizard to database.
        """
        # prepare variables
        user = self.request.user
        sender = user.sender #using the one-to-one relationship
        stripe.api_key = settings.STRIPE_SECRET
        form_data = [form.cleaned_data for form in form_list]
        
        #create instances not yet saved to database (variables incomplete)
        unsaved_amounttosend = forms.AmountToSendForm(form_data[0]).save(commit=False)
        if isinstance(form_data[2]['existing_receiver'], models.Receiver):
            receiver = form_data[2]['existing_receiver']
            unsaved_amounttosend.receiver = receiver
        else:
            unsaved_receiver = forms.ReceiverForm(
                form_data[2],).save(commit=False)
            unsaved_receiver.sender = sender
            receiver = unsaved_receiver.save()
            unsaved_amounttosend.receiver = unsaved_receiver

        # append variables
        unsaved_amounttosend.rate = RATE
        unsaved_amounttosend.sender = sender

        # append variables and actions unique to card and bank
        if unsaved_amounttosend.payment_choice == 'card':
            token = form_data[3]['token']
            amount = unsaved_amounttosend.amount
         
            total_charge_stripe = unsaved_amounttosend.gbp_total() * 100
            
            customer = stripe.Customer.create(
                card= token,
                description= sender
            )
            
            stripe_charge = stripe.Charge.create(
              amount= total_charge_stripe,
              currency="gbp",
              customer=customer.id, # obtained with Stripe.js
              description= 'Total payment and charge for payment to {}'.format(receiver if receiver else unsaved_receiver)
            )
            sender.stripe_id = customer.id
            unsaved_amounttosend.stripe_charge_id = stripe_charge.id
            unsaved_amounttosend.payment_complete = True
            
        if unsaved_amounttosend.payment_choice == 'bank':

pay/templates/pay/amount_calculated.html
{% extends "pay/amount.html" %}


{% block form_inner %}
{% load crispy_forms_tags %}
{% load humanize %}
{{ wizard.form.media }}

<script type="text/javascript">
    $(window).load(function () {
                   $('#myModal').modal('show');
              });
                   
                   $(function () {
                     $(document).on('click', "input[type=button].stay", function () {
                                    $('[rel=popover]').popover('hide');
                                    });
                     
                     $('[rel=popover]').popover({
                                                html: true,
                                                content: function () {
                                                return $('.popover_container').html();
                                                }
                                                });
                     
                     });
                     
    </script>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" data-backdrop="static">
	<div class="modal-dialog">
		<div class="modal-content">
          <div class="modal-header bg-primary">
            <a class="btn btn-primary pull-right bg-primary text-danger" data-original-title="<strong class='text-danger'>Changing Your Mind?</strong>" rel="popover">cancel</a>
            <h4 class="modal-title">Amount Confirmation &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<span class="badge">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</span></h4>
          </div>

            <div class="modal-body">
             <form class="form-horizontal" method="post">
                 <div class="form-group">
                     <label class="col-sm-4 control-label text-primary">Amount to Send:</label>
                     <div class="col-sm-6">
                         <p class="form-control-static">You would like to send &pound;{{ input_amount|intcomma }}.00 </p>
                     </div>
                 </div>
      
            <div class="form-group">
                <label class="col-sm-4 control-label text-primary">Your Charge:</label>
                <div class="col-sm-6">
                    <p class="form-control-static">For {% if payment_choice = 'bank' %} Bank Transfer {% elif payment_choice = 'card' %} Card Payment {% endif %} it's  &pound;{{ charge|intcomma }}.00</p>
                </div>
            </div>
      
            <div class="form-group">
                <label class="col-sm-4 control-label text-primary">Total Plus Charge:</label>
                <div class="col-sm-6">
                    <p class="form-control-static">Your total payment will be &pound;{{ GBP_total|intcomma }}.00</p>
                </div>
            </div>
      
            <div class="form-group">
                <label class="col-sm-4 control-label text-primary">Naira Equivalent:</label>
                <div class="col-sm-6">
                    <p class="form-control-static">The receiver will get &#8358;{{ NGN_total|intcomma }}.00</p>
                </div>
            </div>
                {{ wizard.management_form }}
                {% crispy form %}
             </form>
            </div>
         </div>
        </div>
    </div>
<div class="popover_container" style="display:none">
    <div class="text-warning">
        It's not you it's us. Maybe you'd like to know more. Please visit our <a href='/help/' class="btn btn-s-xxs btn-default btn-rounded">Help</a> pages.
    </div>
    <div class="footer">
        <input type="button" value="Ok I'll Stay" class="btn btn-s-md btn-primary btn-rounded stay"</input>
        <a href={% if user.is_active %} '/mypage/' {% else %} {% url 'home' %} {% endif %} class="btn btn-s-md btn-danger btn-rounded">Cancel Anyway</a>
    </div>
</div>
{% endblock %}

pay/templates/pay/bank_success.html
{% extends "pay/amount.html" %}

{% block form_inner %}
{% load crispy_forms_tags %}
{% load humanize %}
{{ wizard.form.media }}

<script type="text/javascript">
    $(window).load(function () {
                   $('#myModal').modal('show');
                   });
                   $(function () {
                     $(document).on('click', "input[type=button].stay", function () {
                                    $('[rel=popover]').popover('hide');
                                    });
                     
                     $('[rel=popover]').popover({
                                                html: true,
                                                content: function () {
                                                return $('.popover_container').html();
                                                }
                                                });
                     
                     });
                     
    </script>
<div id="myModal" class="modal fade" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
            <div class="modal-header bg-primary">
                <a class="btn btn-primary pull-right bg-primary text-danger" data-original-title="<strong class='text-danger'>Changing Your Mind?</strong>" rel="popover">cancel</a>
                <h4 class="modal-title">That's it! &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <span class="badge">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}</span></h4>
            </div>

            <div class="modal-body">
    <form class="form-horizontal" method="post">
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Just to be sure:</label>
            <div class="col-sm-6">
                <p class="form-control-static">You have chosen to pay by Bank Transfer. </p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Amount to Send:</label>
            <div class="col-sm-6">
                <p class="form-control-static">You are sending &pound;{{ input_amount|intcomma }}.00 </p>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Your Charge:</label>
            <div class="col-sm-6">
                <p class="form-control-static">For {% if payment_choice = 'bank' %} Bank Transfer {% elif payment_choice = 'card' %} Card Payment {% endif %} it's  &pound;{{ charge|intcomma }}.00</p>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Total Plus Charge:</label>
            <div class="col-sm-6">
                <p class="form-control-static">Your total payment will be &pound;{{ GBP_total|intcomma }}.00</p>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Naira Equivalent:</label>
            <div class="col-sm-6">
                <p class="form-control-static">The receiver will get &#8358;{{ NGN_total|intcomma }}.00</p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">All Correct?:</label>
            <div class="col-sm-8">
                <p class="form-control-static">Please pay <strong>&pound;{{ GBP_total|intcomma }}</strong> into the account below</p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label text-success">Our Account:</label>
            <div class="col-sm-8">
                <p class="form-control-static">Kliasoft Ltd<br>
                Sort code: <strong>50271950</strong><br>
                Account number: <strong>200077</strong><br>
                 <em class="text-info">Be sure to quote this reference &nbsp; &nbsp;<span class="glyphicon glyphicon-arrow-right"></span></em><strong id='payment_id' class="text-info"> {{ payment_id }} </strong></p>
            </div>
        </div>
        {{ wizard.management_form }}
        {% crispy form %}
    </form>
            </div>
            <div class="popover_container" style="display:none">
                <div class="text-warning">
                    It's not you it's us. Maybe you'd like to know more. Please visit our <a href='/help/' class="btn btn-s-xxs btn-default btn-rounded">Help</a> pages.
                </div>
                <div class="footer">
                    <input type="button" value="Ok I'll Stay" class="btn btn-s-md btn-primary btn-rounded stay"</input>
                        <a href={% if user.is_active %} '/mypage/' {% else %} {% url 'home' %} {% endif %} class="btn btn-s-md btn-danger btn-rounded">Cancel Anyway</a>
                        </div>
            </div>
{% endblock %}

pay/templates/pay/payment_id.html
<input id="id_bank-payment_id" name="bank-payment_id" type="hidden" value={{payment_id}}>

pay/templates/pay/register.html
{% extends 'pay/index.html' %}'

{% load i18n %}
{% load staticfiles %}

{% block content %}
{% block form_login_logout %}

{% block login_logout %}

<li>
    <div class="m-t-sm"><a href="/login/" class="btn btn-sm btn-success m-l"><strong>Sign In?</strong></a>  </div>
    
</li>
{% endblock %}





<section id="content">
    <div class="bg-primary dk">
<section id="content" class="m-t-lg wrapper-md animated fadeInUp">
	<div class="container aside-xxl">
		<a class="navbar-brand block" href="index.html">RojjaMe</a>
		<section class="panel panel-default bg-white m-t-lg">
			{% if registered %}
            <header id='registered' class="panel-heading text-center">
				<strong>Fantastic! You're registered</strong>
			</header>

<section id="content">

        <h5 class="text-center text-success">Welcome</h5>
        
        <p class="text-center">Click here to continue to <a href='/pay/' id='send' class="btn btn-s-sm btn-primary btn-rounded">send money</a> </p><br>
        <p class="text-center">or go to your <a href='/pay/' class="text-success">Account</a></p><br>
            <p class="text-center">or go to the <a href={% url 'home' %} class="text-success">Homepage</a></p><br>
</section>

			{% else %}
            <header class="panel-heading text-center">
				<strong>Sign Up</strong>
			</header>
            <p class="errornote">
            <div class="form-group">
                <div class="col-sm-10 text-danger text-center">
                    {% if form.errors and not form.non_field_errors %}
                    <p class="errornote form-control-static">
                    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
                    </p>
                    {% endif %}
                    {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                    <p class="errornote form-control-static">
                    {{ error }}
                    </p>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
				<form action="{{ app_path }}" method="post" id="login-form" class="panel-body wrapper-lg" enctype="multipart/form-data">{% csrf_token %}
				  <div class="form-group">
					<label for="id_first_name" class="required control-label">{{ user_form.first_name.label }} </label> 
					<input id="id_first_name" autocomplete="off" type="text" maxlength="254" placeholder="First Name" name="first_name" class="form-control input-sm" required="True">
				  </div>
				  <div class="form-group">
					<label for="id_last_name" class="required control-label">{{ user_form.last_name.label }} </label> 
					<input id="id_last_name" autocomplete="off" type="text" maxlength="254" placeholder="Last Name" name="last_name" class="form-control input-sm" required="True">
				  </div>				  
				  <div class="form-group">
					<label for="id_username" class="required control-label">{{ user_form.username.label }} </label> 
					<input id="id_username" type="text" maxlength="254" autocomplete="off" placeholder="username" name="username" class="form-control input-sm"/>
                        {% if user_form.username.errors %}
                        <div class="alert alert-danger form-control input-sm">{{ user_form.username.errors }}</div>
                        {% endif %}
				  </div>
				  <div class="form-group">
					<label for="id_password" class="required control-label">{% trans 'Password' %}</label>
					<input type="password" autocomplete="off" id="id_password inputPassword" placeholder="Password" class="form-control input-sm" name="password" value="{{ next }}" />
                    {% if user_form.password.errors %}
                    <div class="alert alert-danger form-control input-sm">{{ user_form.password.errors }}</div>
                    {% endif %}
				  </div>
				  <div class="form-group">
					<label for="id_email" class="required control-label">{{ user_form.email.label }} </label> 
					<input id="id_email" type="email" maxlength="254" placeholder="Email" name="email" class="form-control input-sm">
                    {% if user_form.email.errors %}
                    <div class="alert alert-danger form-control input-sm">{{ user_form.email.errors }}</div>
                    {% endif %}
				  </div>
				  <div class="form-group">
					<label for="id_phone" class="required control-label">{{ sender_form.phone.label }} </label> 
					<input id="id_phone" type="text" maxlength="15" placeholder="Phone" name="phone" class="form-control input-sm">
                    {% if sender_form.phone.errors %}
                    <div class="alert alert-danger form-control input-sm">{{ sender_form.phone.errors }}</div>
                    {% endif %}
				  </div>				  

				  <div class="submit-row">
					<label>&nbsp;</label><button id='signup' type="submit" class="btn btn-primary">{% trans 'Sign Up' %}</button>
				  </div>
				  <div class="line line-dashed"></div>
				  <p class="text-muted text-center"><small>Have an account?</small></p>
				  <a href="/login/" class="btn btn-default btn-block">Sign In</a>
				</form>
                {% endif %}
                
                <script type="text/javascript">
                    document.getElementById('id_first_name').focus()
                    </script>
                {% endblock %}
		</section>
	</div>
</section>
</div>
</section>
  <footer id="footer">
    <div class="text-center padder">
      <p>
      <small>RojjaMe Payment Platform<br>&copy; {% now "Y" %}</small>
      </p>
    </div>
  </footer>
{% endblock %}
{% block footer %}
""
{% endblock %}